AddonId: ExtraEmulatorProfiles
Packages:
  - Version: '1.1'
    RequiredApiVersion: '6.2.0'
    ReleaseDate: 2025-03-09
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/2025-01-18/ExtraEmulatorProfiles_1_1.pext
    Changelog:
      - Initial release
  - Version: '1.2'
    RequiredApiVersion: '6.2.0'
    ReleaseDate: 2025-03-29
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/2025-03-29/ExtraEmulatorProfiles_1_2.pext
    Changelog:
      - "Added Azahar 3DS emulator profile (contributed by RetroFlock)"
      - "Added Borked3DS emulator profile"
      - "Added BizHawk PC-FX, 3DS, SG-1000, 32DX and Sega CD profiles (contributed by NinoNook1)"
      - "Fixed Final Burn Neo core profile for RetroArch"
      - "Added .cue extension to Flycast emulator profile"
  - Version: '1.3'
    RequiredApiVersion: '6.2.0'
    ReleaseDate: 2025-06-16
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/2025-06-16/ExtraEmulatorProfiles_1_3.pext
    Changelog:
      - "Base emulator set (the one you get when you reset the changes this plugin makes) is now based on Playnite 10.37"
      - "Retired Lime3DS and shadPS4 patches since these are fixed in Playnite 10.37"
      - "Added RAProject64 emulator profile"
      - "Fixed main menu items not being under the Extensions submenu"
  - Version: '1.4'
    RequiredApiVersion: '6.2.0'
    ReleaseDate: 2025-06-18
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/extraemulatorprofiles1.4/ExtraEmulatorProfiles_1_4.pext
    Changelog:
      - "Added Eden (Switch emulator) profile"
  - Version: '1.5'
    RequiredApiVersion: '6.2.0'
    ReleaseDate: 2025-07-12
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/extraemulatorprofiles1.5/ExtraEmulatorProfiles_1_5.pext
    Changelog:
      - "Added no-gui arguments to PCSX2 and RPCS3 profiles (contributed by reset77)"
      - "Added RetroArch profiles for:"
      - "Arden (Arduboy)"
      - "Arduous (Arduboy)"
      - "Geolith (NeoGeo/Arcade)"
      - "Numero (TI-83)"
      - "ScummVM (PC)"
  - Version: '1.6'
    RequiredApiVersion: '6.2.0'
    ReleaseDate: 2025-08-16
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/2025-08-16/ExtraEmulatorProfiles_1_6.pext
    Changelog:
      - "Added Xenia Canary Netplay profile"
      - "Added rom, dsk, and m3u as ROM file extensions for ares MSX and MSX 2 profiles"
  - Version: '1.7'
    RequiredApiVersion: '6.2.0'
    ReleaseDate: 2025-11-01
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/2025-11-01/ExtraEmulatorProfiles_1_7.pext
    Changelog:
      - "Added TeknoParrot profile (contributed by fresbii)"
      - "Updated shadPS4 profile to use the default emulator instance (contributed by Aladore)"
  - Version: '1.8'
    RequiredApiVersion: '6.2.0'
    ReleaseDate: 2025-11-18
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/2025-11-18/ExtraEmulatorProfiles_1_8.pext
    Changelog:
      - "Fixed FinalBurn Neo profile for RetroArch"
      - "Updated Azahar profile to accept .zcci ROMs (contributed by ppriest)"
      - "Added arcade profiles for Model 2 Emulator, Supermodel (Model 3), and Virtual Pinball X (all contributed by VALIS666)"
