AddonId: ExtraEmulatorProfiles
Packages:
  - Version: 1.1
    RequiredApiVersion: 6.2.0
    ReleaseDate: 2025-03-09
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/2025-01-18/ExtraEmulatorProfiles_1_1.pext
    Changelog:
    - Initial release
  - Version: 1.2
    RequiredApiVersion: 6.2.0
    ReleaseDate: 2025-03-29
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/2025-03-29/ExtraEmulatorProfiles_1_2.pext
    Changelog:
    - "Added Azahar 3DS emulator profile (contributed by RetroFlock)"
    - "Added Borked3DS emulator profile"
    - "Added BizHawk PC-FX, 3DS, SG-1000, 32DX and Sega CD profiles (contributed by NinoNook1)"
    - "Fixed Final Burn Neo core profile for RetroArch"
    - "Added .cue extension to Flycast emulator profile"
  - Version: 1.3
    RequiredApiVersion: 6.2.0
    ReleaseDate: 2025-06-16
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/2025-06-16/ExtraEmulatorProfiles_1_3.pext
    Changelog:
    - "Base emulator set (the one you get when you reset the changes this plugin makes) is now based on Playnite 10.37"
    - "Retired Lime3DS and shadPS4 patches since these are fixed in Playnite 10.37"
    - "Added RAProject64 emulator profile"
    - "Fixed main menu items not being under the Extensions submenu"
  - Version: 1.4
    RequiredApiVersion: 6.2.0
    ReleaseDate: 2025-06-18
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/extraemulatorprofiles1.4/ExtraEmulatorProfiles_1_4.pext
    Changelog:
    - "Added Eden (Switch emulator) profile"
