AddonId: GamersGateLibrary
Packages:
  - Version: 0.1
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-05-29
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/gamersgate0.1/GamersGateLibrary_0_1.pext
    Changelog:
     - Initial release
     - Manual game (un)install
     - Will open visible browser window to import library (to allow user to work around CAPTCHAs)
  - Version: 0.1.1
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-06-04
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/gamersgate0.1.1/GamersGateLibrary_0_1_1.pext
    Changelog:
     - Fixed web request handling
     - Stored DRM type
     - Added more logging
  - Version: 0.1.2
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-11-23
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/2022-11-23/GamersGateLibrary_0_1_2.pext
    Changelog:
     - Fixed missing icon in "Update Game Library" menu
  - Version: 0.2
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2023-12-03
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/2023-12-03/GamersGateLibrary_0_2.pext
    Changelog:
     - Fixed authenticated status not being detected correctly
     - Added setting to import in the background (default for new users)
     - Skip importing known orders (saves time)
