AddonId: GiantBombMetadata
Packages:
  - Version: 0.1
    RequiredApiVersion: 6.8.0
    ReleaseDate: 2022-12-26
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/giantbomb0.1/GiantBombMetadata_0_1.pext
    Changelog:
     - Initial release
  - Version: 0.2
    RequiredApiVersion: 6.8.0
    ReleaseDate: 2022-12-27
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/giantbomb0.2/GiantBombMetadata_0_2.pext
    Changelog:
     - Added game matching based on game links
     - Improved title matching (strips editions and converts roman numerals)
     - Fixed hyperlinks in descriptions not working
     - Added top panel button
     - Removed locations from game property search because locations can't provide a list of associated games
  - Version: 0.3
    RequiredApiVersion: 6.8.0
    ReleaseDate: 2022-12-28
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/giantbomb0.3/GiantBombMetadata_0_3.pext
    Changelog:
     - Added user selection window for backgrounds
     - Fixed character/concept/object/person import window falling off screen
     - Fixed error when imported description contains no hyperlinks
     - Fixed "date modified" field not updating during character/concept/object/person import
  - Version: 0.4
    RequiredApiVersion: 6.8.0
    ReleaseDate: 2023-01-05
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/giantbomb0.4/GiantBombMetadata_0_4.pext
    Changelog:
     - Fixed top panel button option not being applied
     - Fixed search running when the search string is empty
     - Added search by ID for games (such as 3030-18911)
     - Trimmed company forms (such as LTD, LLC, etc) from company names
  - Version: 0.5
    RequiredApiVersion: 6.8.0
    ReleaseDate: 2023-01-12
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/giantbomb0.5/GiantBombMetadata_0_5.pext
    Changelog:
     - Added Features as a target field for mass metadata assignment
     - Added option to only set the first Franchise/Series (collaboration with Jhanlon95)
     - Improved speed of matching games
     - Removed line breaks in search result aliases
  - Version: 0.5.1
    RequiredApiVersion: 6.8.0
    ReleaseDate: 2023-01-19
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/giantbomb0.5.1/GiantBombMetadata_0_5_1.pext
    Changelog:
     - Fixed exception parsing broken description URLs
  - Version: 0.5.2
    RequiredApiVersion: 6.8.0
    ReleaseDate: 2023-03-08
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/giantbomb0.5.2/GiantBombMetadata_0_5_2.pext
    Changelog:
     - Fixed list fields not allowing fallback to other metadata providers when empty
  - Version: 0.6
    RequiredApiVersion: 6.8.0
    ReleaseDate: 2023-04-16
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/2023-04-16/GiantBombMetadata_0_6.pext
    Changelog:
     - Added Locations to bulk property import
     - Added error message when missing API key, and automatic whitespace trimming of API key
  - Version: 0.6.1
    RequiredApiVersion: 6.8.0
    ReleaseDate: 2023-04-18
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/2023-04-18/GiantBombMetadata_0_6_1.pext
    Changelog:
     - Fixed Giant Bomb genres not being imported
  - Version: 0.6.2
    RequiredApiVersion: 6.8.0
    ReleaseDate: 2023-04-23
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/2023-04-23/GiantBombMetadata_0_6_2.pext
    Changelog:
     - Fixed some names being imported with too much surrounding whitespace characters around them
     - Minor settings tweaks
  - Version: 0.7
    RequiredApiVersion: 6.8.0
    ReleaseDate: 2023-05-16
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/2023-05-16/GiantBombMetadata_0_7.pext
    Changelog:
     - Made bulk game property import execution parallel (improves speed significantly)
     - Fixed bulk property assignment window overflowing screen bounds for some multi-monitor setups
     - Small platform matching improvements
  - Version: 0.7.1
    RequiredApiVersion: 6.8.0
    ReleaseDate: 2023-07-26
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/2023-07-26/GiantBombMetadata_0_7_1.pext
    Changelog:
     - Fixed title matching for automated metadata collection for games with alternate titles
  - Version: 0.8
    RequiredApiVersion: 6.8.0
    ReleaseDate: 2024-01-10
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/2024-01-10/GiantBombMetadata_0_8.pext
    Changelog:
     - Added Objects to bulk property import
  - Version: 0.8.1
    RequiredApiVersion: 6.8.0
    ReleaseDate: 2024-02-22
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/2024-02-22/GiantBombMetadata_0_8_1.pext
    Changelog:
     - Optimized game matching for bulk property import
  - Version: 0.8.2
    RequiredApiVersion: 6.8.0
    ReleaseDate: 2024-06-22
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/2024-06-22/GiantBombMetadata_0_8_2.pext
    Changelog:
     - Fixed deadlock when importing properties
  - Version: 0.9
    RequiredApiVersion: 6.8.0
    ReleaseDate: 2024-08-08
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/2024-08-08/GiantBombMetadata_0_9.pext
    Changelog:
     - Added bulk import option to only match filtered games
     - Fixed HTML entities showing up in search result descriptions
     - Improvement in connection handling; less likely to run out of connections
